name: spellcheck

on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 🔤 check spelling # New dictionary words can be added to docs/software.txt and docs/wayfair.txt
        uses: streetsidesoftware/cspell-action@v9.1.0
        with:
          files: "src/docs/**/*.md"
          incremental_files_only: true
